### ISSUE TITLE
颜文字bug提交

### ISSUE THREAD

**Issue by Akasao** [wisaly/WinEmoticons#1]
←_←没想到我是第一个因为不会写英文不要怪我[.
事实上是组合的问题   左边大组合如果在中间插入一个组的话  不会是空白组 而是直接代替原来表情组  而后面的表情组也都一次替换导致最后一个组变成了空白  就是这样[.

**Comment by wisaly** [comment]
@Akasao  感谢提交！我试试啊

**Comment by wisaly** [comment]
bug修复 
c1769da81d615fda2480ed4f95ac18acf04f959d

**Comment by Akasao** [comment]
(๑•̀ㅂ•́)و✧ 加油
